artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: allandclive/chicken-disease-1
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion
